Downgrade ant-junit to version 1.9.16
Otherwise, we can't compile with Java 6. We were using the latest
version (1.10.15) that targets Java 8.

See: https://ant.apache.org/faq.html#java-version

CI Logs building with jdk 6:

```
2025-10-22T22:21:59.2958714Z [INFO] --- compiler:3.11.0:compile (default-compile) @ jaguar2-junit4 ---
2025-10-22T22:21:59.2986083Z [INFO] Toolchain in maven-compiler-plugin: JDK[/opt/hostedtoolcache/Java_Zulu_jdk/6.0.119-119/x64]
2025-10-22T22:21:59.2987483Z [INFO] Changes detected - recompiling the module! :dependency
2025-10-22T22:21:59.2989032Z [INFO] Compiling 3 source files with javac [forked debug target 6] to target/classes
2025-10-22T22:21:59.7495298Z [INFO] -------------------------------------------------------------
2025-10-22T22:21:59.7496143Z [ERROR] COMPILATION ERROR :
2025-10-22T22:21:59.7496599Z [INFO] -------------------------------------------------------------
2025-10-22T22:21:59.7499430Z [ERROR] /home/runner/work/jaguar2/jaguar2/jaguar2-junit4/src/main/java/br/usp/each/saeg/jaguar2/junit/JaguarJUnitResultFormatter.java:[16,51] cannot access org.apache.tools.ant.taskdefs.optional.junit.JUnitResultFormatter
2025-10-22T22:21:59.7501942Z bad class file: ZipFileIndexFileObject[/home/runner/.m2/repository/org/apache/ant/ant-junit/1.10.15/ant-junit-1.10.15.jar(org/apache/tools/ant/taskdefs/optional/junit/JUnitResultFormatter.class)]
2025-10-22T22:21:59.7503281Z class file has wrong version 52.0, should be 50.0
2025-10-22T22:21:59.7503955Z Please remove or make sure it appears in the correct subdirectory of the classpath.
2025-10-22T22:21:59.7504556Z [INFO] 1 error
2025-10-22T22:21:59.7504940Z [INFO] -------------------------------------------------------------
2025-10-22T22:21:59.7505498Z [INFO] ------------------------------------------------------------------------
2025-10-22T22:21:59.7506239Z [INFO] Reactor Summary for jaguar2-parent 0.0.3-SNAPSHOT:
2025-10-22T22:21:59.7506686Z [INFO]
2025-10-22T22:21:59.7507047Z [INFO] Jaguar2 ............................................ SUCCESS [  0.309 s]
2025-10-22T22:21:59.7507682Z [INFO] jaguar2-parent ..................................... SUCCESS [  1.978 s]
2025-10-22T22:21:59.7508305Z [INFO] jaguar2-api ........................................ SUCCESS [  3.519 s]
2025-10-22T22:21:59.7508947Z [INFO] jaguar2-core ....................................... SUCCESS [  1.750 s]
2025-10-22T22:21:59.7509575Z [INFO] jaguar2-commons .................................... SUCCESS [  1.503 s]
2025-10-22T22:21:59.7510240Z [INFO] jaguar2-junit4 ..................................... FAILURE [  0.467 s]
2025-10-22T22:21:59.7510864Z [INFO] jaguar2-providers .................................. SKIPPED
2025-10-22T22:21:59.7511466Z [INFO] jaguar2-ba-dua-provider ............................ SKIPPED
2025-10-22T22:21:59.7512064Z [INFO] jaguar2-jacoco-provider ............................ SKIPPED
2025-10-22T22:21:59.7512663Z [INFO] jaguar2-exporters .................................. SKIPPED
2025-10-22T22:21:59.7513251Z [INFO] jaguar2-csv-exporter ............................... SKIPPED
2025-10-22T22:21:59.7513837Z [INFO] jaguar2-xml-exporter ............................... SKIPPED
2025-10-22T22:21:59.7514420Z [INFO] jaguar2-tests ...................................... SKIPPED
2025-10-22T22:21:59.7514997Z [INFO] jaguar2-api.tests .................................. SKIPPED
2025-10-22T22:21:59.7515579Z [INFO] jaguar2-core.tests ................................. SKIPPED
2025-10-22T22:21:59.7516306Z [INFO] jaguar2-commons.tests .............................. SKIPPED
2025-10-22T22:21:59.7516882Z [INFO] jaguar2-junit4.tests ............................... SKIPPED
2025-10-22T22:21:59.7517444Z [INFO] jaguar2-examples ................................... SKIPPED
2025-10-22T22:21:59.7518005Z [INFO] jaguar2-example-junit4 ............................. SKIPPED
2025-10-22T22:21:59.7518604Z [INFO] jaguar2-example-junit4-ba-dua ...................... SKIPPED
2025-10-22T22:21:59.7519223Z [INFO] jaguar2-example-junit4-jacoco ...................... SKIPPED
2025-10-22T22:21:59.7519837Z [INFO] jaguar2-example-cli-junit4 ......................... SKIPPED
2025-10-22T22:21:59.7520461Z [INFO] jaguar2-example-cli-junit4-jacoco .................. SKIPPED
2025-10-22T22:21:59.7521138Z [INFO] jaguar2-example-ant-junit4 ......................... SKIPPED
2025-10-22T22:21:59.7522043Z [INFO] jaguar2-example-ant-junit4-jacoco .................. SKIPPED
2025-10-22T22:21:59.7522708Z [INFO] jaguar2-example-cli-junit4-ba-dua .................. SKIPPED
2025-10-22T22:21:59.7523608Z [INFO] jaguar2-example-ant-junit4-ba-dua .................. SKIPPED
2025-10-22T22:21:59.7524255Z [INFO] jaguar2-validations ................................ SKIPPED
2025-10-22T22:21:59.7524863Z [INFO] ------------------------------------------------------------------------
2025-10-22T22:21:59.7525344Z [INFO] BUILD FAILURE
2025-10-22T22:21:59.7526408Z [INFO] ------------------------------------------------------------------------
2025-10-22T22:21:59.7526957Z [INFO] Total time:  9.732 s
2025-10-22T22:21:59.7527326Z [INFO] Finished at: 2025-10-22T22:21:59Z
2025-10-22T22:21:59.7527841Z [INFO] ------------------------------------------------------------------------
2025-10-22T22:21:59.7529224Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project jaguar2-junit4: Compilation failure
2025-10-22T22:21:59.7533176Z [ERROR] /home/runner/work/jaguar2/jaguar2/jaguar2-junit4/src/main/java/br/usp/each/saeg/jaguar2/junit/JaguarJUnitResultFormatter.java:[16,51] cannot access org.apache.tools.ant.taskdefs.optional.junit.JUnitResultFormatter
2025-10-22T22:21:59.7536082Z [ERROR] bad class file: ZipFileIndexFileObject[/home/runner/.m2/repository/org/apache/ant/ant-junit/1.10.15/ant-junit-1.10.15.jar(org/apache/tools/ant/taskdefs/optional/junit/JUnitResultFormatter.class)]
2025-10-22T22:21:59.7537490Z [ERROR] class file has wrong version 52.0, should be 50.0
2025-10-22T22:21:59.7538192Z [ERROR] Please remove or make sure it appears in the correct subdirectory of the classpath.
2025-10-22T22:21:59.7538832Z [ERROR] -> [Help 1]
2025-10-22T22:21:59.7540588Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project jaguar2-junit4: Compilation failure
2025-10-22T22:21:59.7543065Z /home/runner/work/jaguar2/jaguar2/jaguar2-junit4/src/main/java/br/usp/each/saeg/jaguar2/junit/JaguarJUnitResultFormatter.java:[16,51] cannot access org.apache.tools.ant.taskdefs.optional.junit.JUnitResultFormatter
2025-10-22T22:21:59.7545491Z bad class file: ZipFileIndexFileObject[/home/runner/.m2/repository/org/apache/ant/ant-junit/1.10.15/ant-junit-1.10.15.jar(org/apache/tools/ant/taskdefs/optional/junit/JUnitResultFormatter.class)]
2025-10-22T22:21:59.7546988Z class file has wrong version 52.0, should be 50.0
2025-10-22T22:21:59.7547626Z Please remove or make sure it appears in the correct subdirectory of the classpath.
2025-10-22T22:21:59.7548099Z
2025-10-22T22:21:59.7548519Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
2025-10-22T22:21:59.7549472Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
2025-10-22T22:21:59.7550410Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
2025-10-22T22:21:59.7551335Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
2025-10-22T22:21:59.7552304Z     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
2025-10-22T22:21:59.7553213Z     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
2025-10-22T22:21:59.7554279Z     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
2025-10-22T22:21:59.7555361Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
2025-10-22T22:21:59.7556594Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
2025-10-22T22:21:59.7557357Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
2025-10-22T22:21:59.7558379Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
2025-10-22T22:21:59.7559132Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
2025-10-22T22:21:59.7560196Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
2025-10-22T22:21:59.7560713Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
2025-10-22T22:21:59.7561121Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
2025-10-22T22:21:59.7561505Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
2025-10-22T22:21:59.7561870Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
2025-10-22T22:21:59.7562228Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
2025-10-22T22:21:59.7562606Z     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2025-10-22T22:21:59.7563070Z     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2025-10-22T22:21:59.7563653Z     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-10-22T22:21:59.7564125Z     at java.lang.reflect.Method.invoke (Method.java:498)
2025-10-22T22:21:59.7564578Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
2025-10-22T22:21:59.7565133Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
2025-10-22T22:21:59.7565983Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
2025-10-22T22:21:59.7566932Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
2025-10-22T22:21:59.7567444Z     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2025-10-22T22:21:59.7568090Z     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2025-10-22T22:21:59.7568753Z     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-10-22T22:21:59.7569408Z     at java.lang.reflect.Method.invoke (Method.java:498)
2025-10-22T22:21:59.7569984Z     at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
2025-10-22T22:21:59.7570616Z     at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
2025-10-22T22:21:59.7571254Z     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
2025-10-22T22:21:59.7571936Z Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
2025-10-22T22:21:59.7573128Z /home/runner/work/jaguar2/jaguar2/jaguar2-junit4/src/main/java/br/usp/each/saeg/jaguar2/junit/JaguarJUnitResultFormatter.java:[16,51] cannot access org.apache.tools.ant.taskdefs.optional.junit.JUnitResultFormatter
2025-10-22T22:21:59.7575232Z bad class file: ZipFileIndexFileObject[/home/runner/.m2/repository/org/apache/ant/ant-junit/1.10.15/ant-junit-1.10.15.jar(org/apache/tools/ant/taskdefs/optional/junit/JUnitResultFormatter.class)]
2025-10-22T22:21:59.7590693Z class file has wrong version 52.0, should be 50.0
2025-10-22T22:21:59.7591476Z Please remove or make sure it appears in the correct subdirectory of the classpath.
2025-10-22T22:21:59.7591981Z
2025-10-22T22:21:59.7592453Z     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1212)
2025-10-22T22:21:59.7593496Z     at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:193)
2025-10-22T22:21:59.7594482Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
2025-10-22T22:21:59.7595535Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
2025-10-22T22:21:59.7596734Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
2025-10-22T22:21:59.7597713Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
2025-10-22T22:21:59.7598699Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
2025-10-22T22:21:59.7599865Z     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
2025-10-22T22:21:59.7600773Z     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
2025-10-22T22:21:59.7602071Z     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
2025-10-22T22:21:59.7603145Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
2025-10-22T22:21:59.7604355Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
2025-10-22T22:21:59.7605812Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
2025-10-22T22:21:59.7607205Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
2025-10-22T22:21:59.7608518Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
2025-10-22T22:21:59.7609450Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
2025-10-22T22:21:59.7610195Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
2025-10-22T22:21:59.7610933Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
2025-10-22T22:21:59.7611569Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
2025-10-22T22:21:59.7612226Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
2025-10-22T22:21:59.7612804Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
2025-10-22T22:21:59.7613201Z     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2025-10-22T22:21:59.7613682Z     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2025-10-22T22:21:59.7614283Z     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-10-22T22:21:59.7614767Z     at java.lang.reflect.Method.invoke (Method.java:498)
2025-10-22T22:21:59.7615248Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
2025-10-22T22:21:59.7616321Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
2025-10-22T22:21:59.7617317Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
2025-10-22T22:21:59.7618302Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
2025-10-22T22:21:59.7619082Z     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2025-10-22T22:21:59.7619821Z     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2025-10-22T22:21:59.7620778Z     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-10-22T22:21:59.7621591Z     at java.lang.reflect.Method.invoke (Method.java:498)
2025-10-22T22:21:59.7622282Z     at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
2025-10-22T22:21:59.7623168Z     at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
2025-10-22T22:21:59.7624007Z     at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
2025-10-22T22:21:59.7624593Z [ERROR]
2025-10-22T22:21:59.7625000Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2025-10-22T22:21:59.7625501Z [ERROR]
2025-10-22T22:21:59.7626330Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2025-10-22T22:21:59.7627221Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2025-10-22T22:21:59.7627763Z [ERROR]
2025-10-22T22:21:59.7628180Z [ERROR] After correcting the problems, you can resume the build with the command
2025-10-22T22:21:59.7628736Z [ERROR]   mvn <args> -rf :jaguar2-junit4
2025-10-22T22:21:59.7791374Z ##[error]Process completed with exit code 1.
```